# Generated by Django 3.2.25 on 2024-06-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                    ("completed", "completed"),
                    ("Returned", "Returned"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
