# Generated by Django 3.2.25 on 2024-06-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.user",
                    ),
                ),
                ("number", models.CharField(blank=True, editable=False, max_length=10)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.user",
                    ),
                ),
                ("number", models.CharField(blank=True, editable=False, max_length=10)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.user",),
        ),
    ]
